server:
  port: 8082

spring:
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        namespace: 4b317e84-4979-4337-8002-fcbfd8a72913
        group: gateway-server
        refreshable-dataids: routes
